/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer-optimized.glb -T 
Files: computer-optimized.glb [486.38KB] > F:\渡一教育\项目实战\3D Web Developer\3dport\public\models\computer-optimized-transformed.glb [39.72KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

type GLTFResult = {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
}

export default function Computer(props: any) {
  const { nodes, materials } = useGLTF('/models/computer-optimized-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_1.geometry} material={materials['ComputerDesk.001']} />
        <mesh castShadow receiveShadow geometry={nodes.Cube000_ComputerDesk_0001_2.geometry} material={materials['FloppyDisk.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-optimized-transformed.glb')
